site_name: Apurva Misra
site_url: https://apurvamisra.com

nav:
  - Speaking: speaking/
  - Hire Me: https://calendly.com/apurva-sentick/60min
  - Blog: blog/

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: "#dcb3f8"
    accent: "#2e990e"
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - header.autohide

extra_css:
  - stylesheets/extra.css

plugins:
  - blog
  - social

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:apurva@sentick.com
      name: Email
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/misraapurva/
      name: LinkedIn
    - icon: fontawesome/brands/medium
      link: https://medium.com/@amisra26
      name: Medium
    - icon: fontawesome/solid/podcast
      link: https://careerdissection.com/
      name: Podcast

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/ApurvaMisra"  target="_blank" rel="noopener">Apurva Misra</a>
