site_name: Blog
theme:
  name: material
  palette:
    primary: teal
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/apurva-misra/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@amisra26

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/ApurvaMisratest"  target="_blank" rel="noopener">Apurva Misra</a>
