site_name: Apurva's Blog
site_url: https://blog.apurvamisra.com

nav:
  - About Me: https://www.apurvamisra.com/speaker
  - Hire Me: https://calendly.com/sentick/30min
  - Blog: blog/

theme:
  name: material
  palette:
    scheme: slate
    primary: "#5cc2db"
    accent: blue grey
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top

extra_css:
  - stylesheets/extra.css

plugins:
  - blog
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/apurva-misra/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@amisra26
    - icon: fontawesome/solid/envelope
      link: mailto:apurva@sentick.com
    - icon: fontawesome/solid/podcast
      link: https://careerdissection.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/ApurvaMisra"  target="_blank" rel="noopener">Apurva Misra</a>
